//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Depozit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Depozit()
        {
            this.Subinventars = new HashSet<Subinventar>();
            this.TransferIntrares = new HashSet<TransferIntrare>();
            this.TransferIntrares1 = new HashSet<TransferIntrare>();
            this.TransferuriIesires = new HashSet<TransferuriIesire>();
            this.TransferuriIesires1 = new HashSet<TransferuriIesire>();
        }
    
        public int idDepozit { get; set; }
        public string nume { get; set; }
        public Nullable<short> idFacultate { get; set; }
        public bool isCentral { get; set; }
        public bool isDepozitCasare { get; set; }
    
        public virtual Facultate Facultate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subinventar> Subinventars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransferIntrare> TransferIntrares { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransferIntrare> TransferIntrares1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransferuriIesire> TransferuriIesires { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransferuriIesire> TransferuriIesires1 { get; set; }
    }
}
