//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subinventar
    {
        public long idSubinventar { get; set; }
        public long idStudent { get; set; }
        public int idAngajat { get; set; }
        public int idDepozit { get; set; }
        public System.DateTime dataPrimire { get; set; }
        public Nullable<System.DateTime> dataPredare { get; set; }
        public long idObiect { get; set; }
        public int cantitate { get; set; }
    
        public virtual Angajat Angajat { get; set; }
        public virtual Depozit Depozit { get; set; }
        public virtual Obiect Obiect { get; set; }
        public virtual Student Student { get; set; }
    }
}
