//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransferuriIesire
    {
        public int idIesire { get; set; }
        public int idDepozitSursa { get; set; }
        public int idDepozitDestinatie { get; set; }
        public long idObiect { get; set; }
        public int cantitate { get; set; }
        public System.DateTime data { get; set; }
        public long nrProcesVerbal { get; set; }
    
        public virtual Depozit Depozit { get; set; }
        public virtual Depozit Depozit1 { get; set; }
        public virtual Obiect Obiect { get; set; }
    }
}
